# Generated by Django 5.0.6 on 2024-06-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroBarra', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Consumicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleConsumicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadLitros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boliche.consumicion')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boliche.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('barra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boliche.barra')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boliche.consumicion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boliche.venta')),
            ],
        ),
    ]
